### ISSUE TITLE
No module named 'langchain_openai'

### ISSUE THREAD

**Issue by YaserOmarAbuQadoom** [svpino/llm#1]
i piped installed langchain openai and did everything as you did but I keep getting this error 
ModuleNotFoundError: No module named 'langchain_openai'
it seems that there are a problem in importing langchain 
any solution ??

**Comment by svpino** [comment]
What version of Python are you using? Sometimes, that causes the issue. I'm running Python 3.9.

**Comment by YaserOmarAbuQadoom** [comment]
I'm using 3.10 
does that cause this problem ??

**Comment by svpino** [comment]
Not sure. I'm using 3.9. If that's not the issue, I'd recommend searching online.

**Comment by svpino** [comment]
Did you ever figure this out?

**Comment by YaserOmarAbuQadoom** [comment]
<img width="946" alt="Screenshot 2024-04-02 at 23 20 32" src="https://github.com/svpino/llm/assets/161254441/06c59c32-bc15-4212-9e66-614be2800485">
i used python 3.9.6 and still have the same problem

**Comment by svpino** [comment]
Okay, I can see you do have the langchain_openai library installed. The problem here is with the Jupyter Kernel.

Your kernel is not installed on the same environment as your library.

Here is what you can do:

Inside the notebook, create a new cell and run this:

```
!pip install langchain_openai
```

Execute this cell. Restart the kernel. It should work.

**Comment by YaserOmarAbuQadoom** [comment]
yes that worked , thanks a lot 
and thanks for the amazing content about LLM one of the best creators I watch , I'm learning a lot because of you 
I'm trying these LLMs to see if it can work with other  languages like Arabic.
