### ISSUE TITLE
[Not an issue] Would like to know which tool is used to create the diagrams

### ISSUE THREAD

**Issue by truonghm** [svpino/llm#2]
Hi Santiago,

Thank you for the very insightful guide. I have a quick question that is not related to the code: Which tool do you used to generate the diagrams [here](https://github.com/svpino/llm/tree/main/images), and also the ones in the notebooks, if you don't might sharing? I find them to be really neat and would like to create something similar for my project if possible. At first glance, the diagrams look like they are built using [excalidraw](https://excalidraw.com/), but not quite. Of course you are not comfortable with sharing this info, it's okay too.

Thank you again, and looking forward to more of your guides and courses!

**Comment by svpino** [comment]
Hey @truonghm, these diagrams are all hand-drawn using an iPad.

**Comment by truonghm** [comment]
> Hey @truonghm, these diagrams are all hand-drawn using an iPad.

thanks for the answer, yes I also did think of that possibility, but felt you must have used a tool since all of your component shapes are super neat. Anw thanks, closing this now!
