### ISSUE TITLE
TypeError: eval() arg 1 must be a string, bytes or code object

### ISSUE THREAD

**Issue by YaserOmarAbuQadoom** [svpino/llm#7]
why I'm getting this error 
for this cell 
if os.path.exists("embedded_sentences.csv"):
    dataset= pd.read_csv("embedded_sentences.csv")
    dataset["embedding"]=dataset.apply(eval).apply(np.array)
else:
    dataset['embedding']=dataset['sentence'].apply(get_embedding)
    dataset.to_csv("embedded_sentences.csv",index=False)

**Comment by svpino** [comment]
What version of Python are you using?

**Comment by YaserOmarAbuQadoom** [comment]
3.9

**Comment by YaserOmarAbuQadoom** [comment]
The Problem solved 
its seems that when I created the notebook I chose python 3.11 
then I changed it after I installed the dependencies to 3.9 I thought that would solve the problem 
I started over and chose 3.9 and solve the problem 
all the time when I was learning machine learning I was using jupter notebook 
so when I switched to vscode I face these kind of problems 
thanks Santiago
